apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oneks-application-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oneks-application-controller-configmap
subjects:
- kind: ServiceAccount
  name: oneks-application-controller
  namespace: oneks-system
