apiVersion: v1
kind: Namespace
metadata:
  name: oneks-system
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/part-of: oneks
---
apiVersion: v1
kind: Namespace
metadata:
  name: oneks-poc-workloads
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/part-of: oneks
