apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capone-cluster-monitor
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: capone-cluster-monitor
  namespace: oneks-system
rules:
- apiGroups: ["oneks.opennebula.io"]
  resources: ["oneksapplications"]
  verbs: ["get", "list", "watch"]
