image:
  repository: ghcr.io/jaimecb/cluster-api-provider-opennebula-monitor
  tag: ""
  pullPolicy: IfNotPresent

monitor:
  endpoint: ""
  clusterID: ""
  openNebulaEndpoint: ""
  key: ""
  authSecretName: ""
  authSecretKey: ONE_AUTH
  httpTimeout: 10s
  podPollInterval: 60s
  resourceConfigNamespace: kube-system
  resourceConfigName: capone-resource-monitor
  resourcePollInterval: 60s
  healthAddress: ":8081"

resourceConfig:
  create: true
  # monitorYaml: |
  #   - apiVersion: apps/v1
  #     resource: deployments
  #     namespace: capone-system
  #     name: capone-controller-manager
  #     path: status.readyReplicas
  monitorYaml: |
    []
