apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oneks-application-controller.name" . }}
  namespace: oneks-system
  labels:
    {{- include "oneks-application-controller.labels" . | nindent 4 }}
automountServiceAccountToken: true
