apiVersion: v1
kind: Secret
metadata:
  name: capone-cluster-monitor
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
stringData:
  MONITOR_KEY: {{ required "monitor.key is required" .Values.monitor.key | quote }}
