apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- crd/oneks.opennebula.io_oneksapplications.yaml
- namespace_application.yaml
- service_account.yaml
- configmap.yaml
- role_application.yaml
- role_binding_application.yaml
- role_helm.yaml
- role_binding_helm.yaml
- role_configmap.yaml
- role_binding_configmap.yaml
- deployment.yaml
images:
- name: application-controller
  newName: ghcr.io/opennebula/oneks-application-controller
  newTag: v0.1.0
